CleanArchMVC.WebUI/Controllers/CategoriesController.cs
using CleanArchMVC.Application.DTOs;
using CleanArchMVC.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchMVC.WebUI.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService, IProductService productService)
        {
            _categoryService = categoryService;


        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<CategoryDTO>>> Index()
        {
            var categories = await _categoryService.GetAllCategoryDTOsAsync();
            return View(categories);

        }

        [HttpGet()]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CategoryDTO categoryDTO)
        {
            if (ModelState.IsValid)
            {
                await _categoryService.CreateCategoryDTOAsync(categoryDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDTO);
        }


        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var categoryDTO = await _categoryService.GetByIdCategoryDTOAsync(id);

            if (categoryDTO == null) return NotFound();

            return View(categoryDTO);


        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Edit(CategoryDTO categoryDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _categoryService.UpdateCategoryDTOAsync(categoryDTO);
                }
                catch (Exception ex)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDTO);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var categoryDTO = await _categoryService.GetByIdCategoryDTOAsync(id);

            if (categoryDTO == null) return NotFound();

            return View(categoryDTO);

        }

        [Authorize(Roles = "Admin")]
        [HttpPost(), ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirme(int? id)
        {
            await _categoryService.DeleteCategoryDTOAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var categoryDTO = await _categoryService.GetByIdCategoryDTOAsync(id);

            if (categoryDTO == null) return NotFound();

            return View(categoryDTO);
        }
    }
}

CleanArchMVC.WebUI/Controllers/ProductController.cs
using CleanArchMVC.Application.DTOs;
using CleanArchMVC.Application.Interfaces;
using CleanArchMVC.Domain.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CleanArchMVC.WebUI.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAllProductDTOsAsync();
            return View(products);
        }

        [HttpGet()]
        public async Task<IActionResult> Create() 
        {

            ViewBag.CategoryId =
                new SelectList(await _categoryService.GetAllCategoryDTOsAsync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductDTO productDTO)
        {
            if (ModelState.IsValid) 
            {
                await _productService.CreateProductDTOAync(productDTO);
                return RedirectToAction(nameof(Index));

            }
            else
            {
                ViewBag.CategoryId =
                new SelectList(await _categoryService.GetAllCategoryDTOsAsync(), "Id", "Name");
                return View();
            }
            
        }

        [Authorize(Roles = "Admin")]
        [HttpGet()]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var productDTO = await _productService.GetByIdProductDTOAsync(id);

            if (productDTO == null) return NotFound();

            var categories = await _categoryService.GetAllCategoryDTOsAsync();

            ViewBag.CategoryId = new SelectList(categories, "Id","Name", productDTO.CategoryId);

            return View(productDTO);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Edit(ProductDTO productDTO)
        {
            if (ModelState.IsValid) 
            {
                await _productService.UpdateProductDTOAsync(productDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(productDTO);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet()]
        public async Task<ActionResult> Delete (int? id)
        {
            if (id == null) return NotFound();

            var product = await _productService.GetByIdProductDTOAsync(id);

            if (product == null) return NotFound();

            return View(product);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost(), ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            await _productService.DeleteProductDTOAsync(id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var product = await _productService.GetByIdProductDTOAsync(id);

            if (product == null) return NotFound();

            return View(product);
        }
    }
}

CleanArchMVC.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanArchMVC.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanArchMVC.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CleanArchMVC.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @await Html.PartialAsync("_LoginPartial")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CleanArchMVC.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>